from func.example import PingCog

BOT_AUTHORIZE_TOKEN="MTIzMTUzNDY1Mjc4Nzc4NTc3OQ.GeUkOq.00YSAZ8r0ald6xKxitwJaXW0I4J9_aLEbFeows"
BOT_COMMAND_PREFIX="!"

BOT_CONFIG_LIST = [PingCog]

from func.test import Test

BOT_AUTHORIZE_TOKEN="MTIzMTUzNDY1Mjc4Nzc4NTc3OQ.GeUkOq.00YSAZ8r0ald6xKxitwJaXW0I4J9_aLEbFeows"
BOT_COMMAND_PREFIX="!"

BOT_CONFIG_LIST = [Test]